### ISSUE TITLE
Rehost to curseforge

### ISSUE THREAD

**Issue by drakosoldier298** [chrrs/scribble#1]
Hello I'm a modpack dev who hosts a modpack named Choclatey [Curseforge](https://www.curseforge.com/minecraft/modpacks/choclatey-re-melted) And on [Modrinth](https://modrinth.com/modpack/choclatey-re-melted) 

I was wondering so that i can have the mod in both sites versions if you would mind hosting the mod on curseforge as well.

**Comment by chrrs** [comment]
It's on CurseForge now! https://www.curseforge.com/minecraft/mc-mods/scribble
