### ISSUE TITLE
Unable to Import Book Files on MacOS

### ISSUE THREAD

**Issue by wiskiw** [chrrs/scribble#11]
### Description
Hi there! I encountered an issue on MacOS while trying to import books in Minecraft.

### Steps to Reproduce
1. Open Minecraft.
2. Take a Book and Quill and the editor.
3. Click on "Load book from file".

### Expected Result
You should be able to select and import book files with the `.book` extension that were previously exported.

### Actual Result
The import dialog does not allow selection of any book files, including those with the `.book` extension.

### Environment 
- Device: MacBook Pro M1 16 GB
- OS: MacOS Sonoma 14.4.1 (23E224)
- Minecraft Version: 1.21

### Screenshots
| Import Dialog |
|---------------|
| ![Screenshot](https://github.com/user-attachments/assets/9ccbc2fa-5700-44b6-884b-9517bf3d430a) |

**Comment by chrrs** [comment]
Thank you for the detailed report! Hmm, I don't have a mac to test this on, as it works fine on Windows, but I have a few ideas on how to fix it! I'll get this done within a few days probably!

**Comment by chrrs** [comment]
This should hopefully be fixed in 1.2.1!

**Comment by wiskiw** [comment]
I just checked on my side, and it works. Thanks! There is no file filter, but according to the commits, it's supposed to be like that for macOS right now. 
I'll try to find a solution to enable the file filter later.
