### ISSUE TITLE
Feature request: Book GUI in the middle of the screen 

### ISSUE THREAD

**Issue by J4PC** [chrrs/scribble#13]
This would greatly improve the readability of books if they were centered vertically.
There is already a [mod ](https://modrinth.com/mod/fixbookgui) that does that, but It would be great to have a all in one package with 
Scribble.

Currently:
![image](https://github.com/user-attachments/assets/d9261223-b7e4-4dcb-b61a-de1eae2720ad)

Request:
![image](https://github.com/user-attachments/assets/5b3216e2-dc2c-4496-b6ab-8e563eaf6858)

**Comment by chrrs** [comment]
Ooh yes, this is something I was thinking about adding as a config option!

**Comment by chrrs** [comment]
This took a bit longer than expected, sorry, but it's in 1.4.0!

**Comment by Fyoncle** [comment]
> This took a bit longer than expected, sorry, but it's in 1.4.0!

Lovely ❤️
