### ISSUE TITLE
Feature: Improve double-click selection

### ISSUE THREAD

**Issue by wiskiw** [chrrs/scribble#17]
It would be nice to double-click on a word without selecting punctuation at the end. This behavior is common in text editors and text input fields, but not for Minecraft.

For example, if you double click on the word "world" in the text below on a Github, it will select only `world`. In Minecraft, it will select `word!!!`.
```
Hello world!!!
```

What do you thing?

**Comment by chrrs** [comment]
Hmm, over everything else I'd want it to be consistent within the game. I don't know if I want to change the behaviour for everything though, since I don't want to touch too much outside of books. In this case, I think I'd rather compromise and just keep the current behaviour.

**Comment by wiskiw** [comment]
kk, I completely understand your point. 
I guess I just gonna fork it and implement a custom selection just for myself. I'm really annoyed by minecraft default selection :)
