### ISSUE TITLE
Incompatible with fixbookgui

### ISSUE THREAD

**Issue by J4PC** [chrrs/scribble#2]
![image](https://github.com/chrrs/scribble/assets/97805057/ac648799-d60b-4bcf-995e-1f3915636506)

If you use the mod [fixbookgui ](https://modrinth.com/mod/fixbookgui) to fix [MC-61489](https://bugs.mojang.com/projects/MC/issues/MC-61489) you can see that the position of the buttons does not depend on the book's actual position.

**Comment by chrrs** [comment]
This is fixed in 1.1.0!
