### ISSUE TITLE
[Crash] Incompatibility with Amendments

### ISSUE THREAD

**Issue by Fyoncle** [chrrs/scribble#21]
It crashes if Scribble present in the same pack with Puzzles lib that is dependency of Better Tridents, Easy Anvils, Easy Magic and such, idk why it does that.

https://mclo.gs/mm7o2eT

**Comment by chrrs** [comment]
It looks like this is actually an issue with the Amendments mod, rather than any of Fuzs' mods. It seems like their changes to the lectern book 'n quill breaks the mod. I'll see what I can do about it, thanks for the report!

![afbeelding](https://github.com/user-attachments/assets/b284e158-12a6-4d8f-9fea-af05aee35976)

**Comment by Fyoncle** [comment]
> It looks like this is actually an issue with the Amendments mod, rather than any of Fuzs' mods. It seems like their changes to the lectern book 'n quill breaks the mod. I'll see what I can do about it, thanks for the report!
> 
> ![afbeelding](https://private-user-images.githubusercontent.com/9766338/378219194-b284e158-12a6-4d8f-9fea-af05aee35976.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NTIzMDMsIm5iZiI6MTcyOTQ1MjAwMywicGF0aCI6Ii85NzY2MzM4LzM3ODIxOTE5NC1iMjg0ZTE1OC0xMmE2LTRkOGYtOWZlYS1hZjA1YWVlMzU5NzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjBUMTkyMDAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTVkYjU2ZDkzMTVmYzgwOGMwZGEwOTZkZjExZDIxOTkxZjJkMTBiOWI0ODk3ZjM1NDUzYzIxMzdiNGViYzQ5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.tEuiK9WEL8rZmVCz_P6vYgFuZ-0BtDSqplzJ0O0PhX8)

This can be disabled via Amendments config and not a problem at all, in the first place i can't even launch my game due to crash with Fuzs Lib

**Comment by chrrs** [comment]
I can still recreate the crash with only Amendments mod installed, and the option disabled, as the reason for the error is still there. I can't recreate the crash with any of Fuzs' mods, so I'm 99% sure it's Amendments. The crash log looks to be slightly misleading in this case.

**Comment by Fyoncle** [comment]
> I can still recreate the crash with only Amendments mod installed, and the option disabled, as the reason for the error is still there. I can't recreate the crash with any of Fuzs' mods, so I'm 99% sure it's Amendments. The crash log looks to be slightly misleading in this case.

Removing all Fuzs's mods are solving the issue for me.

**Comment by chrrs** [comment]
Huh, thats weird. Does it still happen with only Fuzs's mods and Scribble?

**Comment by Fyoncle** [comment]
> Huh, thats weird. Does it still happen with only Fuzs's mods and Scribble?

No, tho it happens this way in my modpack.

I use this version https://modrinth.com/modpack/elysium-days/version/6.0.0

**Comment by Fyoncle** [comment]
> > Huh, thats weird. Does it still happen with only Fuzs's mods and Scribble?
> 
> No, tho it happens this way in my modpack.
> 
> I use this version https://modrinth.com/modpack/elysium-days/version/6.0.0

But in my modpack also removing Amendments helps fixing the crash with keeping Fuzs's mods...

**Comment by chrrs** [comment]
Hmm, I can't recreate it with your modpack. In any case it shouldn't be a huge problem though, as the issue stays the same. It should be a pretty quick fix! Thank you for your help :)

**Comment by Fyoncle** [comment]
> Hmm, I can't recreate it with your modpack. In any case it shouldn't be a huge problem though, as the issue stays the same. It should be a pretty quick fix! Thank you for your help :)

You're welcome, i use a dev version of the modpack which i just slap every single mod to test it before adding it first, it might be one of them honestly.

**Comment by Fyoncle** [comment]
Thanks ❤️
