### ISSUE TITLE
Feature request / feedback - config to hide book import/export

### ISSUE THREAD

**Issue by anoomolu** [chrrs/scribble#27]
Hiya! I've just started using Scribble and I love it, god this would have made writing lore books for my old pack so much simpler 😭 

I was wondering if you'd be willing to add a config that hides the save/load book buttons. I'm sure other people find it handy but it's a little immersion-breaking to see "save to/load from file" when RPing as a weary miner jotting down what happened that day. 

Think the only other piece of feedback I had is regarding the new page button - btw the icon blends in perfectly with the existing GUI buttons so great job there. However, the arrow pointing right also creating new pages feels a bit off. What could be nice is if the arrow only showed up if there were pages to turn to, as is the case with the arrow pointing left. Regardless of whether either of these are implemented, thank you for making such a neat book-editing mod 💜

**Comment by chrrs** [comment]
Hi! Glad you're enjoying the mod!! I made the mod to use for a similar reason myself, so I'm glad that's working for other people too! :)

I completely agree with you about the save/load buttons, they've always felt a little out of place to me, and I haven't been sure how to solve it. I think adding a config option is a good idea!

The insert page button is actually a bit different, it places a new page _before_ the current page, while the arrow creates a new page _after_ the current page. Maybe the wording could be a bit better, but hiding the button would not be right.

Thank you for the feedback!!
