### ISSUE TITLE
(SUGGESTION) Compat with Scholar?

### ISSUE THREAD

**Issue by Diogoess** [chrrs/scribble#29]
Hello!!

Leaving a suggestion for mod combat with scholar! Games starts with both installed but scholar overrides the formatting GUI, and it would be amazing to have both mods working together seamlessly.

That's all!! Love your mod.

**Comment by chrrs** [comment]
Hi! Unfortunately, Scholar completely overhauls the book UI to something very different from vanilla. Making Scribble work with it would basically require a complete rewrite specifically for Scholar, so this is not really possible, sorry!
