### ISSUE TITLE
Bug: Arrow keys UI element flashing 

### ISSUE THREAD

**Issue by J4PC** [chrrs/scribble#30]
When navigating the page via the arrow keys, various UI element start flashing as if they're being selected.
I find this is very annoying when navigating the page.

https://github.com/user-attachments/assets/976885f0-3167-40b9-9b09-6348891d7648

**Comment by chrrs** [comment]
Hmm, I think this is a vanilla issue that Scribble somehow triggers. I'll see if I can fix it!
