### ISSUE TITLE
[Feature Request] Ability to Export Content from Signed Books

### ISSUE THREAD

**Issue by FaNToMaSikkk** [chrrs/scribble#32]
Hello! I would like to request a feature to export the content from signed books in the mod. This would make working with text in these books much easier and more convenient.

![изображение](https://github.com/user-attachments/assets/317f130b-4d67-4cbe-810b-d47e44ce5907)
![изображение](https://github.com/user-attachments/assets/c6e43885-0bbe-465a-9a11-89fe28fd526a)

**Comment by chrrs** [comment]
That sounds reasonable! It will be slightly lossy, as Scribble can't do RGB colors, hover events, click events and custom colors, but that should almost never be an issue anyway.

**Comment by J4PC** [comment]
It would make pirated copies of books a lot easier.
I am not sure I am a fan of that.
Maybe the mod could check if you are the author of the book, or, the more vanilla way, 
you can't save books that are a copy of a copy, just as you are unable to copy such a book in the game.

![image](https://github.com/user-attachments/assets/397e0145-4cf8-4fab-bc85-b7121dd0fbe6)

**Comment by chrrs** [comment]
Hmm, interesting point, hadn't thought of that. I think I'm going to leave it in for now, as copying books will always be possible, even without the mod. Copies of copies have their uses, but I still don't think its an issue, as it's not a 1-to-1 copy (author will be different). If you are using a book as a keycard for example, this won't compromise that. Beyond that, I think it's a very niche use case to want to prevent piracy of books, generally it's not really a big problem.
