### ISSUE TITLE
Mod v1.1.0 unsupported 1.20.1

### ISSUE THREAD

**Issue by FaNToMaSikkk** [chrrs/scribble#4]
![изображение](https://github.com/chrrs/scribble/assets/114670824/a2898d2a-b3d7-44cc-a620-929ccf21ecd4)

The mod ain't running on version 1.20.1/Fabric Loader 0.15.11. Mod version is 1.1.0.

**Comment by chrrs** [comment]
Oops, good find! Should be fixed in 1.1.1!
