### ISSUE TITLE
Feature request: Copy text formatting

### ISSUE THREAD

**Issue by J4PC** [chrrs/scribble#6]
If you want to copy and paste formatted text to a different place or page, it only copies and pastes the plain text without the formatting. It would be very useful if you could just Ctrl C; Ctrl V and the formation of the copied text would be kept.

**Comment by chrrs** [comment]
Yeah, I've noticed that before. I'll need to look into it a bit more on how doable it is, but I'm not sure yet if this is something I can easily do unfortunately. I'll get back on this!

**Comment by J4PC** [comment]
I know that [text-utilities ](https://modrinth.com/mod/text-utilities)has copy and past formatting. But I don't know if their [implementation ](https://modrinth.com/mod/text-utilities) can help.

**Comment by J4PC** [comment]
I know it is not a great question:
When is the version with the merged pull request going to be released?
 
 I would build it myself from the code on GitHub, but I am unable to. Because of 
`Caused by: java.lang.IllegalArgumentException: Cannot nest jars into none mod jar Scribble-1.2.2+mc1.21.jar`
I have no experience with Java, so I am unable to fix it myself. Even Copilot doesn't help.

So my only option is to wait for the official release.

**Comment by chrrs** [comment]
I'll try to release it soon, sorry for the wait! I've been a bit busy and haven't had the time yet, but I'll notify when it releases, should be in the next few days!
