### ISSUE TITLE
Bug?: Empty pages are not removed when pressing done.

### ISSUE THREAD

**Issue by J4PC** [chrrs/scribble#7]
Normally, in vanilla, if pages at the end are empty, they get automatically removed when pressing done. But the mod removes this feature, and you now have to manually delete empty pages at the end of your book. 

I don't know if this is an intended feature of the mod or a bug. 
Personally, I much prefer the vanilla function.

https://github.com/chrrs/scribble/assets/97805057/ea7ad658-c884-4000-b6f9-714a574749ff

https://github.com/chrrs/scribble/assets/97805057/fc29646c-6850-43d7-a117-ef92c24cf6f5

**Comment by chrrs** [comment]
Yes, this was a bug! I've already fixed it, but haven't released a version with the fix yet. Thanks for reporting though!
