### ISSUE TITLE
Feature idea: Jump to first and last page

### ISSUE THREAD

**Issue by J4PC** [chrrs/scribble#8]
When writing longer books, it would be great if you could hold Shift while flipping to the left or right page to go to the first and last page of the book, respectively.

**Comment by chrrs** [comment]
Hmm, I'll think about it! I don't want to overcomplicate the GUI with too many buttons / hidden shortcuts though.

**Comment by chrrs** [comment]
I've made up my mind, this is in 1.1.2!
