### ISSUE TITLE
Feature idea: Ctrl Z

### ISSUE THREAD

**Issue by J4PC** [chrrs/scribble#9]
A Standard feature in nearly every text editing program is undo and redo or rather; Ctrl z, Ctrl y.

This would be great if you had anciently deleted a paragraph or made  any kind of mistake. Where before any mistake was permeant, you can know just undo it.

I know you mentioned that you don't want too many hidden shortcuts, but I think this could be a reasonable one.

**Comment by chrrs** [comment]
Ctrl-Z support would be great! With how the minecraft code around books works though, it might not be that easy to implement, so I think it'll be a bit before I'll get to it.

**Comment by wiskiw** [comment]
Hey @chrrs 
Is there any progress going on right now on this feature? I can try to implement it.

**Comment by chrrs** [comment]
I haven't yet worked on this. It would require keeping track of some kind of undo stack that updates with every action taken. Feel free to try to implement it!
